#!/bin/bash

composer dump-autoload

php artisan migrate:fresh

php artisan clear-compiled
php artisan queue:restart

php artisan route:clear
php artisan cache:clear
php artisan config:clear
php artisan view:clear

php artisan db:seed --class=DatabaseSeeder

exit